
def show_usage
  puts "usage"
  puts""
  puts "#{$0} [verify]"
  puts "verify application and save access token into a file."
  puts""
  puts "#{$0} [toot] (instance's domain) (message)"
  puts "post message to specified domain."
  puts""
  puts "#{$0} [vtoot] (instance's domain) (message) (visibility = direct, private, unlisted or public)"
  puts "post message to specified domain."
  puts""
  puts "#{$0} [reply] (instance's domain) (message) (toot id)"
  puts "post reply to specified domain."
  puts""
  puts "#{$0} [vreply] (instance's domain) (message) (toot id) (visibility = direct, private, unlisted or public)"
  puts "post reply to specified domain."
  puts""
  puts "#{$0} [htl] (instance's domain) "
  puts "show your home time line."
  puts""
  puts "#{$0} [ltl] (instance's domain) "
  puts "show domain's local time line."
  puts""
  puts "#{$0} [ftl] (instance's domain) "
  puts "show domain's federate time line."
  puts""
  puts "#{$0} [shtl] (instance's domain) (interval => 1.0 is 1sec per refresh)"
  puts "streaming mode of htl."
  puts""
  puts "#{$0} [sltl] (instance's domain) (interval => 1.0 is 1sec per refresh)"
  puts "streaming mode of ltl."
  puts""
  puts "#{$0} [sftl] (instance's domain) (interval => 1.0 is 1sec per refresh)"
  puts "streaming mode of ftl."
  puts""
  puts "#{$0} [user] (instance's domain) (user id) "
  puts "show one's user account status."
  puts""
  puts "#{$0} [notify] (instance's domain)"
  puts "show your user notification."
  puts""
  puts "#{$0} [follow] (instance's domain) (user id)"
  puts "follow instance's account."
  puts""
  puts "#{$0} [unfollow] (instance's domain) (user id)"
  puts "unfollow instance's account."
  puts""
  puts "#{$0} [fav] (instance's domain) (toot id)"
  puts "favourite one's toot."
  puts""
  puts "#{$0} [unfav] (instance's domain) (toot id)"
  puts "unfavourite one's toot."
  puts""
  puts "#{$0} [bt] (instance's domain) (toot id)"
  puts "boost one's toot."
  puts""
  puts "#{$0} [unbt] (instance's domain) (toot id)"
  puts "unboost one's toot."
  puts""
end
